<a href="https://colab.research.google.com/github/sammu221166/pratik/blob/main/ans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/iris.csv')
df



sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [5]:
df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [8]:
x=df[['sepal.length','sepal.width','petal.length','petal.width']]
y=df[['variety']]
x
y

variety
0       Setosa
1       Setosa
2       Setosa
3       Setosa
4       Setosa
..         ...
145  Virginica
146  Virginica
147  Virginica
148  Virginica
149  Virginica

[150 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train,x_test,y_train,y_test

(     sepal.length  sepal.width  petal.length  petal.width
 115           6.4          3.2           5.3          2.3
 6             4.6          3.4           1.4          0.3
 19            5.1          3.8           1.5          0.3
 138           6.0          3.0           4.8          1.8
 1             4.9          3.0           1.4          0.2
 ..            ...          ...           ...          ...
 27            5.2          3.5           1.5          0.2
 83            6.0          2.7           5.1          1.6
 92            5.8          2.6           4.0          1.2
 94            5.6          2.7           4.2          1.3
 105           7.6          3.0           6.6          2.1
 
 [120 rows x 4 columns],
      sepal.length  sepal.width  petal.length  petal.width
 62            6.0          2.2           4.0          1.0
 43            5.0          3.5           1.6          0.6
 58            6.6          2.9           4.6          1.3
 98            5.1          2

In [10]:
x_train

sepal.length  sepal.width  petal.length  petal.width
115           6.4          3.2           5.3          2.3
6             4.6          3.4           1.4          0.3
19            5.1          3.8           1.5          0.3
138           6.0          3.0           4.8          1.8
1             4.9          3.0           1.4          0.2
..            ...          ...           ...          ...
27            5.2          3.5           1.5          0.2
83            6.0          2.7           5.1          1.6
92            5.8          2.6           4.0          1.2
94            5.6          2.7           4.2          1.3
105           7.6          3.0           6.6          2.1

[120 rows x 4 columns]

In [11]:
x_test

sepal.length  sepal.width  petal.length  petal.width
62            6.0          2.2           4.0          1.0
43            5.0          3.5           1.6          0.6
58            6.6          2.9           4.6          1.3
98            5.1          2.5           3.0          1.1
111           6.4          2.7           5.3          1.9
45            4.8          3.0           1.4          0.3
3             4.6          3.1           1.5          0.2
40            5.0          3.5           1.3          0.3
31            5.4          3.4           1.5          0.4
11            4.8          3.4           1.6          0.2
0             5.1          3.5           1.4          0.2
79            5.7          2.6           3.5          1.0
10            5.4          3.7           1.5          0.2
120           6.9          3.2           5.7          2.3
32            5.2          4.1           1.5          0.1
140           6.7          3.1           5.6          2.4
146           6.3          2.5           5.0          1.9
46            5.1          3.8           1.6          0.2
78            6.0          2.9           4.5          1.5
130           7.4          2.8           6.1          1.9
23            5.1          3.3           1.7          0.5
125           7.2          3.2           6.0          1.8
134           6.1          2.6           5.6          1.4
131           7.9          3.8           6.4          2.0
148           6.2          3.4           5.4          2.3
48            5.3          3.7           1.5          0.2
70            5.9          3.2           4.8          1.8
30            4.8          3.1           1.6          0.2
18            5.7          3.8           1.7          0.3
91            6.1          3.0           4.6          1.4

In [12]:
y_train

variety
115   Virginica
6        Setosa
19       Setosa
138   Virginica
1        Setosa
..          ...
27       Setosa
83   Versicolor
92   Versicolor
94   Versicolor
105   Virginica

[120 rows x 1 columns]

In [13]:
y_test

variety
62   Versicolor
43       Setosa
58   Versicolor
98   Versicolor
111   Virginica
45       Setosa
3        Setosa
40       Setosa
31       Setosa
11       Setosa
0        Setosa
79   Versicolor
10       Setosa
120   Virginica
32       Setosa
140   Virginica
146   Virginica
46       Setosa
78   Versicolor
130   Virginica
23       Setosa
125   Virginica
134   Virginica
131   Virginica
148   Virginica
48       Setosa
70   Versicolor
30       Setosa
18       Setosa
91   Versicolor

In [14]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [15]:
y_pred=dtc.predict(x_test)
y_pred

array(['Versicolor', 'Setosa', 'Versicolor', 'Versicolor', 'Virginica',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Versicolor', 'Setosa', 'Virginica', 'Setosa', 'Virginica',
       'Virginica', 'Setosa', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Virginica', 'Virginica', 'Virginica', 'Setosa',
       'Virginica', 'Setosa', 'Setosa', 'Versicolor'], dtype=object)

In [16]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [19]:
acc=accuracy_score(y_test,y_pred)
print('accuracy:',acc)
cm=confusion_matrix(y_test,y_pred)
print('confussion_matrix: \n',cm)
cr=classification_report(y_test,y_pred)
print('classification_report:',cr)


accuracy: 0.9666666666666667
confussion_matrix: 
 [[14  0  0]
 [ 0  6  1]
 [ 0  0  9]]
classification_report:               precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        14
  Versicolor       1.00      0.86      0.92         7
   Virginica       0.90      1.00      0.95         9

    accuracy                           0.97        30
   macro avg       0.97      0.95      0.96        30
weighted avg       0.97      0.97      0.97        30

